export const REACT_APP_TALL_BOUND=1.9
export const REACT_APP_HEIGHT_MAX=2.5
export const REACT_APP_ACCESSORIES_THRESHOLD=0.7
export const REACT_APP_AGE_THRESHOLD=21
export const REACT_APP_FACE_THRESHOLD=0.4
export const REACT_APP_DISTANCE_CLOSE=0.5
export const REACT_APP_DISTANCE_FAR=2.0
export const REACT_APP_DISTANCE_MAX=5.0